export const PATH_SERVER = "/server"
export const PATH_AUTH = "/auth"
export const PATH_MAIN = "/main"
export const PATH_SHOP = "/shop"
export const PATH_NOTIFICATION_SETTINGS = "/notification-settings"
